httpServerConfig:
  host: "localhost"
  port: "8080"

postgresConfig:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "avito"

redisConfig:
  host: "localhost"
  port: "6379"
  password: ${CACHE_PASSWORD}

logConfig:
  level: "info"

jwtConfig:
  duration: "24h"
