version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      HTTP_SERVER_HOST: "localhost"
      HTTP_SERVER_PORT: "8080"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DBNAME: "avito"
      LOG_LEVEL: "info"
      JWT_DURATION: "24h"
      JWT_SECRET: "lol"
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "avito"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_DBNAME: "avito"
    depends_on:
      - db
volumes:
  postgres_data:
