run:
	HTTP_SERVER_HOST=localhost HTTP_SERVER_PORT=8080 POSTGRES_HOST=localhost POSTGRES_PORT=5432 POSTGRES_USER=postgres POSTGRES_PASSWORD=postgres POSTGRES_DBNAME=avito REDIS_HOST=localhost REDIS_PORT=6379 CACHE_PASSWORD=your_redis_password LOG_LEVEL=info JWT_DURATION=24h JWT_SECRET=lol go run cmd/main/main.go

migrate:
	HTTP_SERVER_HOST=localhost HTTP_SERVER_PORT=8080 POSTGRES_HOST=localhost POSTGRES_PORT=5432 POSTGRES_USER=postgres POSTGRES_PASSWORD=postgres POSTGRES_DBNAME=avito REDIS_HOST=localhost REDIS_PORT=6379 CACHE_PASSWORD=your_redis_password LOG_LEVEL=info JWT_DURATION=24h JWT_SECRET=lol go run cmd/migrator/main.go